name: ThrowMoney
version: 1.0
description: Throwable Money Plugin
author: undeaD_D
authors: [undeaD_D, DieFriiks, IamNoob, PokemonOnline.xyz] 
website: http://www.pokemon-online.xyz/

main: xyz.diefriiks.tm.Throwmoney
database: false
depends: [Vault]

commands:
  tma:
    description: ThrowMoney Admin Command
    usage: /tma <reset/reload/disable>
  tm:
    description: gives you Money in item form
    usage: /tm <amount>
